# Desafio Data Wrangling

Se Creara un df con la ayuda de una api publica, sobre el valor de 20 principales acciones representativas. Para crear la muestra se seleccioanaran 1000 dias. El df estara compuesto por el valor la accion en columnas y la fecha en cada fila. Luego se comprobara si hay que operar valores nulos, y se realizaran transformaciones a los datos.

Se pasara a cargar un df mediante la api de yahoo finance, para lo cual se utilizo ayuda de chat gpt para mejorar y simplificar el codigo.

## Creacion del DF

**Codigo Principal**

In [2]:

!pip install yfinance
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta, date

def obtener_datos_acciones(simbolos, inicio, fin):
    datos_acciones = {}

    for simbolo in simbolos:
        try:
            # Obtener datos históricos de acciones
            acciones = yf.download(simbolo, start=inicio, end=fin)
            
            if acciones.empty:
                print(f"Error al obtener datos para {simbolo}: No se encontraron datos de acciones.")
                continue

            # Agregar a datos_acciones
            datos_acciones[simbolo] = acciones['Close']

        except Exception as e:
            print(f"Error al obtener datos para {simbolo}: {str(e)}")

    return datos_acciones

if __name__ == "__main__":
    # Símbolos de las 20 acciones más importantes (ejemplo con algunas acciones)
    simbolos_acciones = ["AAPL", "GOOGL", "MSFT", "AMZN", "TSLA", "META", "JPM", "V", "NVDA", "PYPL", 
                         "BA", "INTC", "CSCO", "DIS", "GS", "IBM", "PFE", "WMT", "C", "CVX"]

    # Obtener la fecha de hace 1000 días hábiles
    fin = date.today()
    dias_habiles = 0
    fecha_inicio = fin

    while dias_habiles < 1000:
        fecha_inicio -= timedelta(days=1)
        if fecha_inicio.weekday() < 5:  # 0 a 4 son días hábiles (lunes a viernes)
            dias_habiles += 1

    # Convertir fecha de inicio a formato datetime
    inicio = datetime.combine(fecha_inicio, datetime.min.time())

    datos_acciones = obtener_datos_acciones(simbolos_acciones, inicio, fin)

    # Crear un DataFrame con los datos
    df = pd.DataFrame(datos_acciones)

    # Imprimir el DataFrame
    print(df)

Requirement already satisfied: yfinance in c:\users\nico\anaconda3\lib\site-packages (0.2.32)
Requirement already satisfied: peewee>=3.16.2 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (3.17.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (2022.7)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (2.3.9)
Requirement already satisfied: lxml>=4.9.1 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (4.9.1)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pandas>=1.3.0 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (1.5.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (4.11.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (1.23.5)
Requirement already satisfied: html5lib>=1.1 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: requests>=2.31 in c:\users\nico\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\nico\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: six>=1.9 in c:\users\nico\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\nico\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\nico\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nico\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nico\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nico\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2023.7.22)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nico\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
                  AAPL       GOOGL        MSFT        AMZN        TSLA  \
Date
2020-01-30   80.967499   72.712502  172.779999   93.533997   42.720669
2020-01-31   77.377502   71.639000  170.229996  100.435997   43.371334
2020-02-03   77.165001   74.129997  174.380005  100.209999   52.000000
2020-02-04   79.712502   72.270500  180.119995  102.483498   59.137333
2020-02-05   80.362503   72.302498  179.899994  101.993500   48.980000
...                ...         ...         ...         ...         ...
2023-11-22  191.309998  138.490005  377.850006  146.710007  234.210007
2023-11-24  189.970001  136.690002  377.429993  146.740005  235.449997
2023-11-27  189.789993  136.410004  378.609985  147.729996  236.080002
2023-11-28  190.399994  137.199997  382.700012  147.029999  246.720001
2023-11-29  189.369995  134.990005  378.850006  146.320007  244.139999

                  META         JPM           V        NVDA        PYPL  \
Date
2020-01-30  209.529999  135.889999  208.210007   61.452499  117.120003
2020-01-31  201.910004  132.360001  198.970001   59.107498  113.889999
2020-02-03  204.190002  133.369995  200.809998   60.082500  116.510002
2020-02-04  209.830002  135.289993  203.559998   61.782501  120.080002
2020-02-05  210.110001  137.589996  202.809998   62.689999  119.720001
...                ...         ...         ...         ...         ...
2023-11-22  341.489990  153.330002  253.720001  487.160004   56.340000
2023-11-24  338.230011  153.539993  254.300003  477.760010   55.759998
2023-11-27  334.700012  153.190002  254.139999  482.420013   56.389999
2023-11-28  338.989990  153.539993  252.940002  478.209991   58.470001
2023-11-29  332.200012  154.320007  254.229996  481.399994   57.970001

                    BA       INTC       CSCO         DIS          GS  \
Date
2020-01-30  323.299988  66.470001  47.240002  137.809998  244.130005
2020-01-31  318.269989  63.930000  45.970001  138.309998  237.750000
2020-02-03  316.000000  64.419998  46.529999  141.320007  239.009995
2020-02-04  317.940002  65.459999  47.619999  144.729996  241.940002
2020-02-05  329.549988  67.339996  48.450001  141.369995  244.300003
...                ...        ...        ...         ...         ...
2023-11-22  219.910004  43.669998  48.080002   95.070000  338.640015
2023-11-24  220.000000  43.959999  48.360001   96.059998  339.149994
2023-11-27  219.300003  44.080002  47.930000   95.169998  337.709991
2023-11-28  222.369995  44.230000  47.849998   92.500000  337.649994
2023-11-29  224.429993  44.939999  48.049999   92.500000  340.260010

                   IBM        PFE         WMT          C         CVX
Date
2020-01-30  130.755264  35.170776  116.580002  77.430000  111.400002
2020-01-31  137.409180  35.332069  114.489998  74.410004  107.139999
2020-02-03  139.837479  35.588234  114.269997  75.129997  106.279999
2020-02-04  142.552582  35.759014  115.269997  76.500000  106.849998
2020-02-05  149.455063  36.214420  116.809998  78.849998  110.279999
...                ...        ...         ...        ...         ...
2023-11-22  155.130005  30.320000  154.669998  45.020000  144.330002
2023-11-24  155.179993  30.500000  156.059998  45.230000  144.899994
2023-11-27  155.570007  30.139999  156.770004  45.080002  144.360001
2023-11-28  155.649994  29.690001  158.639999  44.860001  145.509995
2023-11-29  156.410004  30.080000  156.080002  45.750000  143.910004

[966 rows x 20 columns]

--------------------------------------------------------------------------------------------------------------------------------

**Muestra del df**

In [3]:
df.head()

,AAPL,GOOGL,MSFT,AMZN,TSLA,META,JPM,V,NVDA,PYPL,BA,INTC,CSCO,DIS,GS,IBM,PFE,WMT,C,CVX
Date,,,,,,,,,,,,,,,,,,,,
2020-01-30,80.967499,72.712502,172.779999,93.533997,42.720669,209.529999,135.889999,208.210007,61.452499,117.120003,323.299988,66.470001,47.240002,137.809998,244.130005,130.755264,35.170776,116.580002,77.430000,111.400002
2020-01-31,77.377502,71.639000,170.229996,100.435997,43.371334,201.910004,132.360001,198.970001,59.107498,113.889999,318.269989,63.930000,45.970001,138.309998,237.750000,137.409180,35.332069,114.489998,74.410004,107.139999
2020-02-03,77.165001,74.129997,174.380005,100.209999,52.000000,204.190002,133.369995,200.809998,60.082500,116.510002,316.000000,64.419998,46.529999,141.320007,239.009995,139.837479,35.588234,114.269997,75.129997,106.279999
2020-02-04,79.712502,72.270500,180.119995,102.483498,59.137333,209.830002,135.289993,203.559998,61.782501,120.080002,317.940002,65.459999,47.619999,144.729996,241.940002,142.552582,35.759014,115.269997,76.500000,106.849998
2020-02-05,80.362503,72.302498,179.899994,101.993500,48.980000,210.110001,137.589996,202.809998,62.689999,119.720001,329.549988,67.339996,48.450001,141.369995,244.300003,149.455063,36.214420,116.809998,78.849998,110.279999

-------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------

## Transformacion de datos

--------------------------------------------------------------------------------------------------------------------------------

**Cantidad de filas y columnas**

In [7]:
df.shape

(966, 20)

**Tipo de datos**

In [10]:
df.dtypes

AAPL     float64
GOOGL    float64
MSFT     float64
AMZN     float64
TSLA     float64
META     float64
JPM      float64
V        float64
NVDA     float64
PYPL     float64
BA       float64
INTC     float64
CSCO     float64
DIS      float64
GS       float64
IBM      float64
PFE      float64
WMT      float64
C        float64
CVX      float64
dtype: object

**Analizamos cantidad de nulos**

In [6]:
df.isnull().sum()

AAPL     0
GOOGL    0
MSFT     0
AMZN     0
TSLA     0
META     0
JPM      0
V        0
NVDA     0
PYPL     0
BA       0
INTC     0
CSCO     0
DIS      0
GS       0
IBM      0
PFE      0
WMT      0
C        0
CVX      0
dtype: int64

**Cambiamos el valor de dolar a pesos en una nueva columna**

In [9]:
# Creacion de un nuevo dataframe
valor_dolar = 370
df_pesos = df * valor_dolar

# Filtramos a 2 decimales
df_pesos = df_pesos.round(2)

df_pesos.head()

,AAPL,GOOGL,MSFT,AMZN,TSLA,META,JPM,V,NVDA,PYPL,BA,INTC,CSCO,DIS,GS,IBM,PFE,WMT,C,CVX
Date,,,,,,,,,,,,,,,,,,,,
2020-01-30,29957.97,26903.63,63928.6,34607.58,15806.65,77526.1,50279.3,77037.7,22737.42,43334.4,119621.0,24593.9,17478.8,50989.7,90328.1,48379.45,13013.19,43134.6,28649.1,41218.0
2020-01-31,28629.68,26506.43,62985.1,37161.32,16047.39,74706.7,48973.2,73618.9,21869.77,42139.3,117759.9,23654.1,17008.9,51174.7,87967.5,50841.40,13072.87,42361.3,27531.7,39641.8
2020-02-03,28551.05,27428.10,64520.6,37077.70,19240.00,75550.3,49346.9,74299.7,22230.53,43108.7,116920.0,23835.4,17216.1,52288.4,88433.7,51739.87,13167.65,42279.9,27798.1,39323.6
2020-02-04,29493.63,26740.09,66644.4,37918.89,21880.81,77637.1,50057.3,75317.2,22859.53,44429.6,117637.8,24220.2,17619.4,53550.1,89517.8,52744.46,13230.84,42649.9,28305.0,39534.5
2020-02-05,29734.13,26751.92,66563.0,37737.59,18122.60,77740.7,50908.3,75039.7,23195.30,44296.4,121933.5,24915.8,17926.5,52306.9,90391.0,55298.37,13399.34,43219.7,29174.5,40803.6